default: styles/glitchy-witchy.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
boring-default: styles/application.scss
rip-witches: styles/witches-town.scss
glitchy-witchy-plainer: styles/glitchy-witchy-plainer.scss
